sudo: required

services:
  - python
  
env:
  - distribution: solita/centos-systemd-ssh
    version: 7
    islandora_distro: centos/7
    user: vagrant
  - distribution: solita/ubuntu-systemd-ssh
    version: 16.04
    islandora_distro: ubuntu/xenial64
    user: ubuntu
    
before_install:
  - sudo docker pull ${distribution}:${version}
  - sudo docker build --no-cache --rm --file=.travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible ${TRAVIS_BUILD_DIR}
  - sudo docker run --detach --privileged --tty --name="${TRAVIS_BUILD_ID}" ${distribution}-${version}:ansible

script:  
  - sudo docker ps -a
  - sudo docker exec --env ANSIBLE_FORCE_COLOR=1 ${TRAVIS_BUILD_ID} ansible-galaxy -r requirements.yml --roles-path=roles/external install
  - sudo docker exec --env ANSIBLE_FORCE_COLOR=1 ${TRAVIS_BUILD_ID} ansible-playbook -i inventory/vagrant -u ${user} -e islandora_distro=\"${islandora_distro}\" -v --syntax-check playbook.yml
  - sudo docker exec --env ANSIBLE_FORCE_COLOR=1 ${TRAVIS_BUILD_ID} ansible-playbook -i inventory/vagrant -u ${user} -e islandora_distro=\"${islandora_distro}\" -v playbook.yml
  