sudo: required

services:
  - docker
  
env:
  - distribution: centos
    version: 7
    islandora_distro: centos/7
    user: vagrant
    init: /usr/lib/systemd/systemd
  - distribution: ubuntu
    version: xenial
    islandora_distro: ubuntu/xenial64
    user: ubuntu
    init: /lib/systemd/systemd
    
before_install:
  - sudo docker pull ${distribution}:${version}
  - sudo docker build --no-cache --rm --file=.travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'

script:  
  - sudo docker run --detach --volume="${TRAVIS_BUILD_DIR}" --name "${TRAVIS_BUILD_ID}" ${distribution}-${version}:ansible ${init}
  - sudo docker ps -a
  - sudo docker exec --env ANSIBLE_FORCE_COLOR=1 ${TRAVIS_BUILD_ID} ansible-playbook -i inventory/vagrant -u ${user} -e islandora_distro=\"${islandora_distro}\" -v --syntax-check playbook.yml
  - sudo docker exec --env ANSIBLE_FORCE_COLOR=1 ${TRAVIS_BUILD_ID} ansible-playbook -i inventory/vagrant -u ${user} -e islandora_distro=\"${islandora_distro}\" -v playbook.yml
  